/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForGymOwnersRouteImport } from './routes/for-gym-owners'
import { Route as ForGymChainsRouteImport } from './routes/for-gym-chains'
import { Route as ForBoutiqueStudiosRouteImport } from './routes/for-boutique-studios'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as FeaturesQrAttendanceRouteImport } from './routes/features.qr-attendance'
import { Route as FeaturesPaymentsRouteImport } from './routes/features.payments'
import { Route as FeaturesMembershipManagementRouteImport } from './routes/features.membership-management'
import { Route as FeaturesMemberAppRouteImport } from './routes/features.member-app'
import { Route as FeaturesClassBookingRouteImport } from './routes/features.class-booking'
import { Route as FeaturesBrandingWhiteLabelRouteImport } from './routes/features.branding-white-label'
import { Route as FeaturesAnalyticsReportsRouteImport } from './routes/features.analytics-reports'
import { Route as CompareReponeVsZenplannerRouteImport } from './routes/compare.repone-vs-zenplanner'
import { Route as CompareReponeVsMindbodyRouteImport } from './routes/compare.repone-vs-mindbody'
import { Route as CompareReponeVsGlofoxRouteImport } from './routes/compare.repone-vs-glofox'
import { Route as CompareReponeVsExcelWhatsappRouteImport } from './routes/compare.repone-vs-excel-whatsapp'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQrManagementRouteImport } from './routes/admin.qr-management'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMembershipsRouteImport } from './routes/admin.memberships'
import { Route as AdminMembershipRequestsRouteImport } from './routes/admin.membership-requests'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminGuestPassesRouteImport } from './routes/admin.guest-passes'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as MemberSupportTicketsRouteImport } from './routes/_member.support-tickets'
import { Route as MemberProgressRouteImport } from './routes/_member.progress'
import { Route as MemberProfileRouteImport } from './routes/_member.profile'
import { Route as MemberPaymentsRouteImport } from './routes/_member.payments'
import { Route as MemberNotificationsRouteImport } from './routes/_member.notifications'
import { Route as MemberMembershipPlansRouteImport } from './routes/_member.membership-plans'
import { Route as MemberDashboardRouteImport } from './routes/_member.dashboard'
import { Route as MemberClassesRouteImport } from './routes/_member.classes'
import { Route as MemberBuyMembershipRouteImport } from './routes/_member.buy-membership'
import { Route as MemberAttendanceRouteImport } from './routes/_member.attendance'
import { Route as AdminMembersAddRouteImport } from './routes/admin.members.add'
import { Route as AdminMembersMemberIdRouteImport } from './routes/admin.members.$memberId'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForGymOwnersRoute = ForGymOwnersRouteImport.update({
  id: '/for-gym-owners',
  path: '/for-gym-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForGymChainsRoute = ForGymChainsRouteImport.update({
  id: '/for-gym-chains',
  path: '/for-gym-chains',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBoutiqueStudiosRoute = ForBoutiqueStudiosRouteImport.update({
  id: '/for-boutique-studios',
  path: '/for-boutique-studios',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesQrAttendanceRoute = FeaturesQrAttendanceRouteImport.update({
  id: '/features/qr-attendance',
  path: '/features/qr-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesPaymentsRoute = FeaturesPaymentsRouteImport.update({
  id: '/features/payments',
  path: '/features/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesMembershipManagementRoute =
  FeaturesMembershipManagementRouteImport.update({
    id: '/features/membership-management',
    path: '/features/membership-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesMemberAppRoute = FeaturesMemberAppRouteImport.update({
  id: '/features/member-app',
  path: '/features/member-app',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesClassBookingRoute = FeaturesClassBookingRouteImport.update({
  id: '/features/class-booking',
  path: '/features/class-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesBrandingWhiteLabelRoute =
  FeaturesBrandingWhiteLabelRouteImport.update({
    id: '/features/branding-white-label',
    path: '/features/branding-white-label',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesAnalyticsReportsRoute =
  FeaturesAnalyticsReportsRouteImport.update({
    id: '/features/analytics-reports',
    path: '/features/analytics-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareReponeVsZenplannerRoute =
  CompareReponeVsZenplannerRouteImport.update({
    id: '/compare/repone-vs-zenplanner',
    path: '/compare/repone-vs-zenplanner',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareReponeVsMindbodyRoute = CompareReponeVsMindbodyRouteImport.update({
  id: '/compare/repone-vs-mindbody',
  path: '/compare/repone-vs-mindbody',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareReponeVsGlofoxRoute = CompareReponeVsGlofoxRouteImport.update({
  id: '/compare/repone-vs-glofox',
  path: '/compare/repone-vs-glofox',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareReponeVsExcelWhatsappRoute =
  CompareReponeVsExcelWhatsappRouteImport.update({
    id: '/compare/repone-vs-excel-whatsapp',
    path: '/compare/repone-vs-excel-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQrManagementRoute = AdminQrManagementRouteImport.update({
  id: '/qr-management',
  path: '/qr-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipRequestsRoute = AdminMembershipRequestsRouteImport.update({
  id: '/membership-requests',
  path: '/membership-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestPassesRoute = AdminGuestPassesRouteImport.update({
  id: '/guest-passes',
  path: '/guest-passes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const MemberSupportTicketsRoute = MemberSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProgressRoute = MemberProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberPaymentsRoute = MemberPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => MemberRoute,
} as any)
const MemberNotificationsRoute = MemberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMembershipPlansRoute = MemberMembershipPlansRouteImport.update({
  id: '/membership-plans',
  path: '/membership-plans',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MemberRoute,
} as any)
const MemberClassesRoute = MemberClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBuyMembershipRoute = MemberBuyMembershipRouteImport.update({
  id: '/buy-membership',
  path: '/buy-membership',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAttendanceRoute = MemberAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MemberRoute,
} as any)
const AdminMembersAddRoute = AdminMembersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminMembersRoute,
} as any)
const AdminMembersMemberIdRoute = AdminMembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AdminMembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkin': typeof CheckinRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/for-boutique-studios': typeof ForBoutiqueStudiosRoute
  '/for-gym-chains': typeof ForGymChainsRoute
  '/for-gym-owners': typeof ForGymOwnersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/attendance': typeof MemberAttendanceRoute
  '/buy-membership': typeof MemberBuyMembershipRoute
  '/classes': typeof MemberClassesRoute
  '/dashboard': typeof MemberDashboardRoute
  '/membership-plans': typeof MemberMembershipPlansRoute
  '/notifications': typeof MemberNotificationsRoute
  '/payments': typeof MemberPaymentsRoute
  '/profile': typeof MemberProfileRoute
  '/progress': typeof MemberProgressRoute
  '/support-tickets': typeof MemberSupportTicketsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/guest-passes': typeof AdminGuestPassesRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/membership-requests': typeof AdminMembershipRequestsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/qr-management': typeof AdminQrManagementRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/compare/repone-vs-excel-whatsapp': typeof CompareReponeVsExcelWhatsappRoute
  '/compare/repone-vs-glofox': typeof CompareReponeVsGlofoxRoute
  '/compare/repone-vs-mindbody': typeof CompareReponeVsMindbodyRoute
  '/compare/repone-vs-zenplanner': typeof CompareReponeVsZenplannerRoute
  '/features/analytics-reports': typeof FeaturesAnalyticsReportsRoute
  '/features/branding-white-label': typeof FeaturesBrandingWhiteLabelRoute
  '/features/class-booking': typeof FeaturesClassBookingRoute
  '/features/member-app': typeof FeaturesMemberAppRoute
  '/features/membership-management': typeof FeaturesMembershipManagementRoute
  '/features/payments': typeof FeaturesPaymentsRoute
  '/features/qr-attendance': typeof FeaturesQrAttendanceRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/admin/members/$memberId': typeof AdminMembersMemberIdRoute
  '/admin/members/add': typeof AdminMembersAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkin': typeof CheckinRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/for-boutique-studios': typeof ForBoutiqueStudiosRoute
  '/for-gym-chains': typeof ForGymChainsRoute
  '/for-gym-owners': typeof ForGymOwnersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/attendance': typeof MemberAttendanceRoute
  '/buy-membership': typeof MemberBuyMembershipRoute
  '/classes': typeof MemberClassesRoute
  '/dashboard': typeof MemberDashboardRoute
  '/membership-plans': typeof MemberMembershipPlansRoute
  '/notifications': typeof MemberNotificationsRoute
  '/payments': typeof MemberPaymentsRoute
  '/profile': typeof MemberProfileRoute
  '/progress': typeof MemberProgressRoute
  '/support-tickets': typeof MemberSupportTicketsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/guest-passes': typeof AdminGuestPassesRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/membership-requests': typeof AdminMembershipRequestsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/qr-management': typeof AdminQrManagementRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/compare/repone-vs-excel-whatsapp': typeof CompareReponeVsExcelWhatsappRoute
  '/compare/repone-vs-glofox': typeof CompareReponeVsGlofoxRoute
  '/compare/repone-vs-mindbody': typeof CompareReponeVsMindbodyRoute
  '/compare/repone-vs-zenplanner': typeof CompareReponeVsZenplannerRoute
  '/features/analytics-reports': typeof FeaturesAnalyticsReportsRoute
  '/features/branding-white-label': typeof FeaturesBrandingWhiteLabelRoute
  '/features/class-booking': typeof FeaturesClassBookingRoute
  '/features/member-app': typeof FeaturesMemberAppRoute
  '/features/membership-management': typeof FeaturesMembershipManagementRoute
  '/features/payments': typeof FeaturesPaymentsRoute
  '/features/qr-attendance': typeof FeaturesQrAttendanceRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/compare': typeof CompareIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/admin/members/$memberId': typeof AdminMembersMemberIdRoute
  '/admin/members/add': typeof AdminMembersAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_member': typeof MemberRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkin': typeof CheckinRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/for-boutique-studios': typeof ForBoutiqueStudiosRoute
  '/for-gym-chains': typeof ForGymChainsRoute
  '/for-gym-owners': typeof ForGymOwnersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/_member/attendance': typeof MemberAttendanceRoute
  '/_member/buy-membership': typeof MemberBuyMembershipRoute
  '/_member/classes': typeof MemberClassesRoute
  '/_member/dashboard': typeof MemberDashboardRoute
  '/_member/membership-plans': typeof MemberMembershipPlansRoute
  '/_member/notifications': typeof MemberNotificationsRoute
  '/_member/payments': typeof MemberPaymentsRoute
  '/_member/profile': typeof MemberProfileRoute
  '/_member/progress': typeof MemberProgressRoute
  '/_member/support-tickets': typeof MemberSupportTicketsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/guest-passes': typeof AdminGuestPassesRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/membership-requests': typeof AdminMembershipRequestsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/qr-management': typeof AdminQrManagementRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/compare/repone-vs-excel-whatsapp': typeof CompareReponeVsExcelWhatsappRoute
  '/compare/repone-vs-glofox': typeof CompareReponeVsGlofoxRoute
  '/compare/repone-vs-mindbody': typeof CompareReponeVsMindbodyRoute
  '/compare/repone-vs-zenplanner': typeof CompareReponeVsZenplannerRoute
  '/features/analytics-reports': typeof FeaturesAnalyticsReportsRoute
  '/features/branding-white-label': typeof FeaturesBrandingWhiteLabelRoute
  '/features/class-booking': typeof FeaturesClassBookingRoute
  '/features/member-app': typeof FeaturesMemberAppRoute
  '/features/membership-management': typeof FeaturesMembershipManagementRoute
  '/features/payments': typeof FeaturesPaymentsRoute
  '/features/qr-attendance': typeof FeaturesQrAttendanceRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/admin/members/$memberId': typeof AdminMembersMemberIdRoute
  '/admin/members/add': typeof AdminMembersAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/checkin'
    | '/contact'
    | '/demo'
    | '/for-boutique-studios'
    | '/for-gym-chains'
    | '/for-gym-owners'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms-of-service'
    | '/testimonials'
    | '/attendance'
    | '/buy-membership'
    | '/classes'
    | '/dashboard'
    | '/membership-plans'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/progress'
    | '/support-tickets'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/guest-passes'
    | '/admin/members'
    | '/admin/membership-requests'
    | '/admin/memberships'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/qr-management'
    | '/admin/reports'
    | '/admin/settings'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/compare/repone-vs-excel-whatsapp'
    | '/compare/repone-vs-glofox'
    | '/compare/repone-vs-mindbody'
    | '/compare/repone-vs-zenplanner'
    | '/features/analytics-reports'
    | '/features/branding-white-label'
    | '/features/class-booking'
    | '/features/member-app'
    | '/features/membership-management'
    | '/features/payments'
    | '/features/qr-attendance'
    | '/blog/'
    | '/case-studies/'
    | '/compare/'
    | '/features/'
    | '/admin/members/$memberId'
    | '/admin/members/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/checkin'
    | '/contact'
    | '/demo'
    | '/for-boutique-studios'
    | '/for-gym-chains'
    | '/for-gym-owners'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms-of-service'
    | '/testimonials'
    | '/attendance'
    | '/buy-membership'
    | '/classes'
    | '/dashboard'
    | '/membership-plans'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/progress'
    | '/support-tickets'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/guest-passes'
    | '/admin/members'
    | '/admin/membership-requests'
    | '/admin/memberships'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/qr-management'
    | '/admin/reports'
    | '/admin/settings'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/compare/repone-vs-excel-whatsapp'
    | '/compare/repone-vs-glofox'
    | '/compare/repone-vs-mindbody'
    | '/compare/repone-vs-zenplanner'
    | '/features/analytics-reports'
    | '/features/branding-white-label'
    | '/features/class-booking'
    | '/features/member-app'
    | '/features/membership-management'
    | '/features/payments'
    | '/features/qr-attendance'
    | '/blog'
    | '/case-studies'
    | '/compare'
    | '/features'
    | '/admin/members/$memberId'
    | '/admin/members/add'
  id:
    | '__root__'
    | '/'
    | '/_member'
    | '/about'
    | '/admin'
    | '/checkin'
    | '/contact'
    | '/demo'
    | '/for-boutique-studios'
    | '/for-gym-chains'
    | '/for-gym-owners'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms-of-service'
    | '/testimonials'
    | '/_member/attendance'
    | '/_member/buy-membership'
    | '/_member/classes'
    | '/_member/dashboard'
    | '/_member/membership-plans'
    | '/_member/notifications'
    | '/_member/payments'
    | '/_member/profile'
    | '/_member/progress'
    | '/_member/support-tickets'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/guest-passes'
    | '/admin/members'
    | '/admin/membership-requests'
    | '/admin/memberships'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/qr-management'
    | '/admin/reports'
    | '/admin/settings'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/compare/repone-vs-excel-whatsapp'
    | '/compare/repone-vs-glofox'
    | '/compare/repone-vs-mindbody'
    | '/compare/repone-vs-zenplanner'
    | '/features/analytics-reports'
    | '/features/branding-white-label'
    | '/features/class-booking'
    | '/features/member-app'
    | '/features/membership-management'
    | '/features/payments'
    | '/features/qr-attendance'
    | '/blog/'
    | '/case-studies/'
    | '/compare/'
    | '/features/'
    | '/admin/members/$memberId'
    | '/admin/members/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemberRoute: typeof MemberRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckinRoute: typeof CheckinRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  ForBoutiqueStudiosRoute: typeof ForBoutiqueStudiosRoute
  ForGymChainsRoute: typeof ForGymChainsRoute
  ForGymOwnersRoute: typeof ForGymOwnersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CompareReponeVsExcelWhatsappRoute: typeof CompareReponeVsExcelWhatsappRoute
  CompareReponeVsGlofoxRoute: typeof CompareReponeVsGlofoxRoute
  CompareReponeVsMindbodyRoute: typeof CompareReponeVsMindbodyRoute
  CompareReponeVsZenplannerRoute: typeof CompareReponeVsZenplannerRoute
  FeaturesAnalyticsReportsRoute: typeof FeaturesAnalyticsReportsRoute
  FeaturesBrandingWhiteLabelRoute: typeof FeaturesBrandingWhiteLabelRoute
  FeaturesClassBookingRoute: typeof FeaturesClassBookingRoute
  FeaturesMemberAppRoute: typeof FeaturesMemberAppRoute
  FeaturesMembershipManagementRoute: typeof FeaturesMembershipManagementRoute
  FeaturesPaymentsRoute: typeof FeaturesPaymentsRoute
  FeaturesQrAttendanceRoute: typeof FeaturesQrAttendanceRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-gym-owners': {
      id: '/for-gym-owners'
      path: '/for-gym-owners'
      fullPath: '/for-gym-owners'
      preLoaderRoute: typeof ForGymOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-gym-chains': {
      id: '/for-gym-chains'
      path: '/for-gym-chains'
      fullPath: '/for-gym-chains'
      preLoaderRoute: typeof ForGymChainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-boutique-studios': {
      id: '/for-boutique-studios'
      path: '/for-boutique-studios'
      fullPath: '/for-boutique-studios'
      preLoaderRoute: typeof ForBoutiqueStudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/qr-attendance': {
      id: '/features/qr-attendance'
      path: '/features/qr-attendance'
      fullPath: '/features/qr-attendance'
      preLoaderRoute: typeof FeaturesQrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/payments': {
      id: '/features/payments'
      path: '/features/payments'
      fullPath: '/features/payments'
      preLoaderRoute: typeof FeaturesPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/membership-management': {
      id: '/features/membership-management'
      path: '/features/membership-management'
      fullPath: '/features/membership-management'
      preLoaderRoute: typeof FeaturesMembershipManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/member-app': {
      id: '/features/member-app'
      path: '/features/member-app'
      fullPath: '/features/member-app'
      preLoaderRoute: typeof FeaturesMemberAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/class-booking': {
      id: '/features/class-booking'
      path: '/features/class-booking'
      fullPath: '/features/class-booking'
      preLoaderRoute: typeof FeaturesClassBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/branding-white-label': {
      id: '/features/branding-white-label'
      path: '/features/branding-white-label'
      fullPath: '/features/branding-white-label'
      preLoaderRoute: typeof FeaturesBrandingWhiteLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/analytics-reports': {
      id: '/features/analytics-reports'
      path: '/features/analytics-reports'
      fullPath: '/features/analytics-reports'
      preLoaderRoute: typeof FeaturesAnalyticsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/repone-vs-zenplanner': {
      id: '/compare/repone-vs-zenplanner'
      path: '/compare/repone-vs-zenplanner'
      fullPath: '/compare/repone-vs-zenplanner'
      preLoaderRoute: typeof CompareReponeVsZenplannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/repone-vs-mindbody': {
      id: '/compare/repone-vs-mindbody'
      path: '/compare/repone-vs-mindbody'
      fullPath: '/compare/repone-vs-mindbody'
      preLoaderRoute: typeof CompareReponeVsMindbodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/repone-vs-glofox': {
      id: '/compare/repone-vs-glofox'
      path: '/compare/repone-vs-glofox'
      fullPath: '/compare/repone-vs-glofox'
      preLoaderRoute: typeof CompareReponeVsGlofoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/repone-vs-excel-whatsapp': {
      id: '/compare/repone-vs-excel-whatsapp'
      path: '/compare/repone-vs-excel-whatsapp'
      fullPath: '/compare/repone-vs-excel-whatsapp'
      preLoaderRoute: typeof CompareReponeVsExcelWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qr-management': {
      id: '/admin/qr-management'
      path: '/qr-management'
      fullPath: '/admin/qr-management'
      preLoaderRoute: typeof AdminQrManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/membership-requests': {
      id: '/admin/membership-requests'
      path: '/membership-requests'
      fullPath: '/admin/membership-requests'
      preLoaderRoute: typeof AdminMembershipRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guest-passes': {
      id: '/admin/guest-passes'
      path: '/guest-passes'
      fullPath: '/admin/guest-passes'
      preLoaderRoute: typeof AdminGuestPassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_member/support-tickets': {
      id: '/_member/support-tickets'
      path: '/support-tickets'
      fullPath: '/support-tickets'
      preLoaderRoute: typeof MemberSupportTicketsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/progress': {
      id: '/_member/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof MemberProgressRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/profile': {
      id: '/_member/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/payments': {
      id: '/_member/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof MemberPaymentsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/notifications': {
      id: '/_member/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MemberNotificationsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/membership-plans': {
      id: '/_member/membership-plans'
      path: '/membership-plans'
      fullPath: '/membership-plans'
      preLoaderRoute: typeof MemberMembershipPlansRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/dashboard': {
      id: '/_member/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/classes': {
      id: '/_member/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof MemberClassesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/buy-membership': {
      id: '/_member/buy-membership'
      path: '/buy-membership'
      fullPath: '/buy-membership'
      preLoaderRoute: typeof MemberBuyMembershipRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/attendance': {
      id: '/_member/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof MemberAttendanceRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/members/add': {
      id: '/admin/members/add'
      path: '/add'
      fullPath: '/admin/members/add'
      preLoaderRoute: typeof AdminMembersAddRouteImport
      parentRoute: typeof AdminMembersRoute
    }
    '/admin/members/$memberId': {
      id: '/admin/members/$memberId'
      path: '/$memberId'
      fullPath: '/admin/members/$memberId'
      preLoaderRoute: typeof AdminMembersMemberIdRouteImport
      parentRoute: typeof AdminMembersRoute
    }
  }
}

interface MemberRouteChildren {
  MemberAttendanceRoute: typeof MemberAttendanceRoute
  MemberBuyMembershipRoute: typeof MemberBuyMembershipRoute
  MemberClassesRoute: typeof MemberClassesRoute
  MemberDashboardRoute: typeof MemberDashboardRoute
  MemberMembershipPlansRoute: typeof MemberMembershipPlansRoute
  MemberNotificationsRoute: typeof MemberNotificationsRoute
  MemberPaymentsRoute: typeof MemberPaymentsRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberProgressRoute: typeof MemberProgressRoute
  MemberSupportTicketsRoute: typeof MemberSupportTicketsRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAttendanceRoute: MemberAttendanceRoute,
  MemberBuyMembershipRoute: MemberBuyMembershipRoute,
  MemberClassesRoute: MemberClassesRoute,
  MemberDashboardRoute: MemberDashboardRoute,
  MemberMembershipPlansRoute: MemberMembershipPlansRoute,
  MemberNotificationsRoute: MemberNotificationsRoute,
  MemberPaymentsRoute: MemberPaymentsRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberProgressRoute: MemberProgressRoute,
  MemberSupportTicketsRoute: MemberSupportTicketsRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface AdminMembersRouteChildren {
  AdminMembersMemberIdRoute: typeof AdminMembersMemberIdRoute
  AdminMembersAddRoute: typeof AdminMembersAddRoute
}

const AdminMembersRouteChildren: AdminMembersRouteChildren = {
  AdminMembersMemberIdRoute: AdminMembersMemberIdRoute,
  AdminMembersAddRoute: AdminMembersAddRoute,
}

const AdminMembersRouteWithChildren = AdminMembersRoute._addFileChildren(
  AdminMembersRouteChildren,
)

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminGuestPassesRoute: typeof AdminGuestPassesRoute
  AdminMembersRoute: typeof AdminMembersRouteWithChildren
  AdminMembershipRequestsRoute: typeof AdminMembershipRequestsRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQrManagementRoute: typeof AdminQrManagementRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminGuestPassesRoute: AdminGuestPassesRoute,
  AdminMembersRoute: AdminMembersRouteWithChildren,
  AdminMembershipRequestsRoute: AdminMembershipRequestsRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQrManagementRoute: AdminQrManagementRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemberRoute: MemberRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckinRoute: CheckinRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  ForBoutiqueStudiosRoute: ForBoutiqueStudiosRoute,
  ForGymChainsRoute: ForGymChainsRoute,
  ForGymOwnersRoute: ForGymOwnersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TestimonialsRoute: TestimonialsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CompareReponeVsExcelWhatsappRoute: CompareReponeVsExcelWhatsappRoute,
  CompareReponeVsGlofoxRoute: CompareReponeVsGlofoxRoute,
  CompareReponeVsMindbodyRoute: CompareReponeVsMindbodyRoute,
  CompareReponeVsZenplannerRoute: CompareReponeVsZenplannerRoute,
  FeaturesAnalyticsReportsRoute: FeaturesAnalyticsReportsRoute,
  FeaturesBrandingWhiteLabelRoute: FeaturesBrandingWhiteLabelRoute,
  FeaturesClassBookingRoute: FeaturesClassBookingRoute,
  FeaturesMemberAppRoute: FeaturesMemberAppRoute,
  FeaturesMembershipManagementRoute: FeaturesMembershipManagementRoute,
  FeaturesPaymentsRoute: FeaturesPaymentsRoute,
  FeaturesQrAttendanceRoute: FeaturesQrAttendanceRoute,
  BlogIndexRoute: BlogIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
